name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }} / ${{ matrix.python-version }} ${{ matrix.suffix }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os: [ Ubuntu, Windows ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pyprojectx
        uses: actions/cache@v3
        with:
          path: .pyprojectx
          key: ${{ hashFiles('pyproject.toml') }}-${{ runner.os }}-${{ matrix.python-version }}-pyprojectx
      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ hashFiles('uv.lock') }}-${{ runner.os }}-${{ matrix.python-version }}-venv

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test and build
        run: |
          python pw build
